---
image: ubuntu:18.04

stages:
  - cross_environment
  - flatpak_build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_FOLDER: build
  DEB_PPA: "ppa:remmina-ppa-team/remmina-next"
  FREERDP_DAILY_PPA: "ppa:remmina-ppa-team/freerdp-daily"
  DOCKER_IMAGE: "ubuntu:xenial"
  CMAKE_BUILD_OPTIONS: "-DCMAKE_BUILD_TYPE=Release -DWITH_APPINDICATOR=on"
  FLATPAK_ARCH: x86_64

before_script:
  - mkdir -p .flatpak-builder/cache

# TODO: We should create a job for each distro and test the compile correcthly
#       but _only_ if triggered at certain conditions (releases, tag, etc)
#       http://docs.gitlab.com/ee/ci/yaml/README.html#only-and-except-simplified
# This is an example for Ubuntu
ubuntu:devel:
  # image: ubuntu:devel
  stage: cross_environment
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq software-properties-common
                          python3-software-properties
    - apt-add-repository $FREERDP_DAILY_PPA -y
    - apt-get update -qq
    - apt-get install -y -qq build-essential git-core cmake libssl-dev \
    libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev \
    libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev \
    libxrandr-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    libxi-dev libavutil-dev libavcodec-dev libxtst-dev libgtk-3-dev \
    libgcrypt11-dev libssh-dev libpulse-dev libvte-2.91-dev libxkbfile-dev \
    libtelepathy-glib-dev libjpeg-dev libgnutls28-dev libgnome-keyring-dev \ 
    libavahi-ui-gtk3-dev libvncserver-dev libappindicator3-dev intltool \ 
    libsecret-1-dev libwebkit2gtk-4.0-dev libsystemd-dev libsoup2.4-dev \
    libjson-glib-dev libavresample-dev libfreerdp2-dev

  script:
    - mkdir $BUILD_FOLDER
    - cmake -B$BUILD_FOLDER -H. $CMAKE_BUILD_OPTIONS
    - make VERBOSE=1 -C $BUILD_FOLDER
  only:
    # - branches
    - tags
    - web
    - schedules

flatpak:test:
  # image: fedora:latest
  stage: flatpak_build
  variables:
    BUNDLE: "remmina-dev.flatpak"
    FLATPAK_PPA: "ppa:alexlarsson/flatpak"
    FLATHUB_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq software-properties-common
                          python-software-properties
    - add-apt-repository $FLATPAK_PPA -y
    - apt-get update -qq
    - apt-get install -y -qq flatpak-builder flatpak build-essential git-core
    - flatpak --user remote-add --if-not-exists flathub $FLATHUB_REPO
  script:
    - /bin/sh -xe ./flatpak/flatpak-build.sh
  artifacts:
    paths:
      - flatpak/${BUNDLE}
    expire_in: 30 days
  cache:
    paths:
      - flatpak/.flatpak-builder/cache
  only:
    # - branches
    - tags
    - web
    - schedules
