---
image: ubuntu:16.04

stages:
  - cross_environment
  - flatpak_build

variables:
  BUILD_FOLDER: build
  DEB_PPA: "ppa:remmina-ppa-team/remmina-next"
  FREERDP_DAILY_PPA: "ppa:remmina-ppa-team/freerdp-daily"
  FLATPAK_PPA: "ppa:alexlarsson/flatpak"
  DOCKER_IMAGE: "ubuntu:xenial"
  CMAKE_BUILD_OPTIONS: "-DCMAKE_BUILD_TYPE=Release -DWITH_APPINDICATOR=on"
  FLATPAK_ARCH: x86_64

before_script:
  - apt-get update -qq
  - apt-get install -y -qq software-properties-common python-software-properties
  - apt-add-repository $FREERDP_DAILY_PPA -y
  - add-apt-repository $FLATPAK_PPA -y
  - apt-get update -qq
  - apt-get install -y -qq build-essential git-core cmake
                           libssl-dev libx11-dev libxext-dev libxinerama-dev
                           libxcursor-dev libxdamage-dev libxv-dev
                           libcups2-dev libxml2 libxml2-dev libxkbfile-dev
                           libasound2-dev libxrandr-dev libgstreamer0.10-dev
                           libgstreamer-plugins-base0.10-dev libgstreamer1.0-dev
                           libgstreamer-plugins-base1.0-dev libxi-dev
                           libavutil-dev libavcodec-dev libxtst-dev
                           libgtk-3-dev libgcrypt11-dev libssh-dev libpulse-dev
                           libvte-2.91-dev libxkbfile-dev libfreerdp-dev
                           libtelepathy-glib-dev libjpeg-dev libgnutls-dev
                           libgnome-keyring-dev libavahi-ui-gtk3-dev
                           libvncserver-dev libappindicator3-dev intltool
                           libsecret-1-dev libwebkit2gtk-3.0-dev libsoup2.4-dev
                           libjson-glib-dev libspice-protocol-dev
                           libspice-client-gtk-3.0-dev flatpak-builder docker.io
  # validate docker is functional
  - systemctl start docker
  - docker info

# TODO: We should create a job for each distro and test the compile correcthly
#       but _only_ if triggered at certain conditions (releases, tag, etc)
#       http://docs.gitlab.com/ee/ci/yaml/README.html#only-and-except-simplified
# This is an example for Ubuntu
ubuntu:devel:
  # image: ubuntu:devel
  stage: cross_environment
  script:
    - mkdir $BUILD_FOLDER
    - cmake -B$BUILD_FOLDER -H. $CMAKE_BUILD_OPTIONS
    - make VERBOSE=1 -C $BUILD_FOLDER
    # only:
    # - tags
    # - web
    # - schedules

flatpak:test:
  # image: fedora:latest
  stage: flatpak_build
  script:
    - docker build -t flatpak -f ./flatpak/Dockerfile .
    - docker run --privileged --env=FLATPAK_ARCH=$FLATPAK_ARCH flatpak
